Repository JuliaRobotics/RoMEPlotting.jl, pull requests merged in 2020-12, with the labels that each got.

#134 some docs improvements
  src/RobotViz.jl
  src/SolverVisualization.jl
Labels: documentation, maintenance

#132 Fix plotCliqDownMsgs
  src/SolverVisualization.jl
Labels: bug fix

#137 drop Grahps.jl, compat
  Project.toml
  src/Deprecated.jl
  src/NeedsFixing.jl
  src/SolverVisualization.jl
  test/testPlotKDE.jl
Labels: compat, deprecations, testing, versioning

#141 general maintenance and compat
  Project.toml
  src/RobotViz.jl
Labels: compat, maintenance
