Repository JuliaRobotics/RoMEPlotting.jl, pull requests merged in 2022-04, with the labels that each got.

#201 Remove println in covEllipseParameterized
  src/services/PlotEllipseUtils.jl
Labels: maintenance

#202 compat and depr names
  Project.toml
  src/PlotVariables.jl
  src/RobotViz.jl
  test/testPose2Point2Plotting.jl
Labels: documentation, deprecations, upstream, maintenance

#203 v0.9.1-rc1
  Project.toml
  src/PlotVariables.jl
  src/RobotViz.jl
  src/services/PlotEllipseUtils.jl
  test/testPose2Point2Plotting.jl
Labels: release
